### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by posix4e** [thesam/rustboot#3]
I tried reducing it to the minimum main and I get
rustc -O --target i686-unknown-linux-gnu --crate-type lib -o main.o --emit obj -C target-cpu=generic main.rs
error: requires `sized` lang_item
error: aborting due to previous error
Makefile:13: recipe for target 'main.o' failed

**Comment by thesam** [comment]
It's getting harder and harder to get something usable without libcore.
Maybe it's time to add it as a dependency (as I've done in rOSt).
